- name: Run HTTPD
  docker_container:
    name: http-server
    image: clemg73/tp-devops-http-server:latest
    pull: yes
    networks:
      - name: app-proxy-network
    ports:
      - "80:80"
      - "8080:8080"
