- name: Run App
  docker_container:
    name: simple-api
    image: clemg73/tp-devops-simple-api:latest
    pull: yes
    networks:
      - name: db-app-network
      - name: app-proxy-network
    env_file: /setup/.env
