- name: Run Databse
  docker_container:
    name: database
    image: clemg73/tp-devops-database:latest
    pull: yes
    networks:
      - name: db-app-network
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file: /setup/.env