services:

  database:
    build: "database"
    environment:
      - POSTGRES_PASSWORD=pwd
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - db-app-network

  simple-api:
    build: "simple-api"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PASSWORD=pwd
    networks:
      - db-app-network
      - app-proxy-network

  front:
    build: "devops-front-main"
    networks:
      - app-proxy-network

  httpd:
    build: "http-server"
    ports:
      - "80:80"
    networks:
      - app-proxy-network

networks:
  db-app-network:
  app-proxy-network:

volumes:
  db-volume :