name: CI delivery 2025
on:
  workflow_run:
    workflows: ['CI devops 2025']
    types: [completed]
    branches-ignore:
      - "develop"

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    steps:

        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Login to DockerHub
          run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build image and push backend
          uses: docker/build-push-action@v3
          with:
            context: ./tp-devops-correction-docker/simple-api
            tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
            push: ${{ github.ref == 'refs/heads/main' }}

        - name: Build image and push database
          uses: docker/build-push-action@v3
          with:
            context: ./tp-devops-correction-docker/database
            tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest
            push: ${{ github.ref == 'refs/heads/main' }}

        - name: Build image and push httpd
          uses: docker/build-push-action@v3
          with:
            context: ./tp-devops-correction-docker/http-server
            tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-http-server:latest
            push: ${{ github.ref == 'refs/heads/main' }}