name: CI delivery 2025
on:
  #workflow_run:
  #  workflows: ['CI develop 2025']
  #  types: [completed]
  #  branches:
  #    - "main"
  push:
  pull_request:


jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write SSH private key to file
        run: |
          sudo mkdir /ssh
          sudo touch /ssh/id_rsa
          sudo echo "${{ secrets.ID_RSA }}" > /ssh/id_rsa
          sudo chmod 600 /ssh/id_rsa
          # Optionnel : Vérification du contenu de la clé (ne jamais afficher la clé réelle dans les logs)
          echo "SSH private key written successfully."

      - name: Install Maven
        run: sudo apt update && sudo apt install -y maven

      - name: Extract version from pom.xml
        id: versioning
        run: |
          cd ./src/tp-devops-correction-docker/simple-api
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./src/tp-devops-correction-docker/simple-api
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:${{ env.VERSION }}
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./src/tp-devops-correction-docker/database
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:${{ env.VERSION }}
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./src/tp-devops-correction-docker/http-server
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-http-server:${{ env.VERSION }}
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-http-server:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push front
        uses: docker/build-push-action@v3
        with:
          context: ./src/tp-devops-correction-docker/devops-front-main
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-front:${{ env.VERSION }}
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-front:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push ansible
        uses: docker/build-push-action@v3
        with:
          context: ./ansible
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-ansible:${{ env.VERSION }}
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-ansible:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Run Docker container
        run: |
          docker run ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-ansible:latest

  cancel-pr-on-failure:
    needs: [build-and-push-docker-image]
    if: failure()
    runs-on: ubuntu-22.04
    steps: 
      - name: Close PR on Failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(jq --raw-output .pull_request.number < "$GITHUB_EVENT_PATH")
          echo "Closing PR #$pr_number due to pipeline failure"
          curl -X PATCH \-H "Authorization: token $GITHUB_TOKEN" \-H "Accept: application/vnd.github.v3+json" \https://api.github.com/repos/$%7B%7B github.repository }}/pulls/$pr_number \-d '{"state":"closed"}'