name: CI delivery 2025
on:
  workflow_run:
    workflows: ['CI develop 2025']
    types: [completed]
    branches:
      - "main"

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Maven
        run: sudo apt update && sudo apt install -y maven

      - name: Extract version from pom.xml
        id: versioning
        run: |
          cd ./tp-devops-correction-docker/simple-api
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV


      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./tp-devops-correction-docker/simple-api
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:${{ env.VERSION }}
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./tp-devops-correction-docker/database
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:${{ env.VERSION }}
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./tp-devops-correction-docker/http-server
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-http-server:latest
            ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-http-server:${{ env.VERSION }}
          push: ${{ github.ref == 'refs/heads/main' }}
