name: CI develop 2025
on:
  push:
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build and test with Maven
        run: |
          cd ./tp-devops-correction-docker/simple-api
          mvn clean verify

  sonarcloud: 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Send to Sonarcloud
        run: |
          cd ./tp-devops-correction-docker/simple-api
          mvn -B verify sonar:sonar -Dsonar.projectKey=clemg73_clemg73 -Dsonar.organization=clemg73 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./pom.xml

  cancel-pr-on-failure:
    needs: [test-backend, sonar-backend]
    if: failure()
    runs-on: ubuntu-22.04
    steps: 
      name: Close PR on Failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(jq --raw-output .pull_request.number < "$GITHUB_EVENT_PATH")
          echo "Closing PR #$pr_number due to pipeline failure"
          curl -X PATCH \-H "Authorization: token $GITHUB_TOKEN" \-H "Accept: application/vnd.github.v3+json" \https://api.github.com/repos/$%7B%7B github.repository }}/pulls/$pr_number \-d '{"state":"closed"}'