name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: #TODO 
  pull_request:

jobs:
  build-and-push-docker-image:
  needs: test-backend
  runs-on: ubuntu-22.04

  steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: ./tp-devops-correction-docker/simple-api

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./tp-devops-correction-docker/simple-api
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./tp-devops-correction-docker/database
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./tp-devops-correction-docker/http-server
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-http-server:latest